### PR TITLE
Improve performance of publication

### PR DESCRIPTION
**Pull request by dmlloyd**
Acquiring a logger inside a loop causes repeated stack traversals. The log event generally does not need to have a category object, so we populate it lazily instead. Eliminate repeated construction of filter objects, and inline the filter checking logic.

### CODE REVIEW

**Comment by ivassile** [comment]
@dmlloyd Can we merge this PR and tag version 1.3.1? We have to include it in the upcoming EAP 7.4.18. Thanks!

**Comment by dmlloyd** [comment]
WDYT @jamezp?

**Review by jamezp — APPROVED** [review]

**Comment by ivassile** [comment]
> Sorry, I completely spaced this. It's merged, do we need a release too?

Yes please.

**Comment by jamezp** [comment]
@ivassile Done https://github.com/jboss-logging/log4j-jboss-logmanager/releases/tag/1.3.1.Final

**Pull request merged**
